In [2]:
import pandas as pd 
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('/home/cabito/Documents/trabajos-Estadistica/Carseats.csv')

In [5]:
display(data.head())
print(data.shape)

,Unnamed: 0,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,1,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,2,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,3,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,4,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,5,4.15,141,64,3,340,128,Bad,38,13,Yes,No

(400, 12)

In [9]:
data.head()

,Unnamed: 0,Sales,CompPrice,Income,Advertising,Population,Price,Age,Education,ShelveLoc_Bad,ShelveLoc_Good,ShelveLoc_Medium,Urban_No,Urban_Yes,US_No,US_Yes
0,1,9.50,138,73,11,276,120,42,17,1,0,0,0,1,0,1
1,2,11.22,111,48,16,260,83,65,10,0,1,0,0,1,0,1
2,3,10.06,113,35,10,269,80,59,12,0,0,1,0,1,0,1
3,4,7.40,117,100,4,466,97,55,14,0,0,1,0,1,0,1
4,5,4.15,141,64,3,340,128,38,13,1,0,0,0,1,1,0

In [ ]:
tree_class = sk.tree.DecisionTreeClassifier(data)
tree_reg = sk.tree.DecisionTreeRegressor(data)
bagg = sk.ensemble.BaggingClassifier(data)

In [2]:
import numpy as np
import pandas as pd
import patsy as pt
from mpl_toolkits.mplot3d import Axes3D

display(HTML(graph._repr_svg_()))

clf.score(X, y)
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from IPython.display import HTML
import copy
import warnings
warnings.filterwarnings('ignore')
from sklearn import tree
import graphviz
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn import datasets
from sklearn.model_selection import cross_val_score


carseats_df = pd.read_csv('Carseats.csv')
# Check for missing values
assert carseats_df.isnull().sum().sum() == 0
# Drop unused index
carseats_df = carseats_df.drop('Unnamed: 0', axis=1)
# Create binary variable High 1 if Sales > 8
carseats_df['High'] = (carseats_df['Sales'] > 8).astype(np.float64)
# Create index for training set
np.random.seed(1)
train = np.random.random(len(carseats_df)) > 0.5
carseats_df.head()
#We now use the respective function to fit a classification tree in order to predict High using all variables but Sales.
#Please draw the tree and select the accuracy of the model for the training data.
# Use all features except response features
# No intercept
f = 'High ~ 0 + ' + ' + '.join(carseats_df.columns.drop(['Sales', 'High']))
y, X = pt.dmatrices(f, carseats_df)
y = y.flatten()
# Fit Sklearns tree classifier
clf = tree.DecisionTreeClassifier(max_depth=4).fit(X, y)
# Visualise the tree with GraphViz
dot_data = tree.export_graphviz(clf, out_file=None,
feature_names=X.design_info.column_names,
class_names=['Low', 'High'],
filled=True, rounded=True)
graph = graphviz.Source(dot_data)
display(HTML(graph._repr_svg_()))
clf.score(X, y)

NameError: name 'HTML' is not defined

In [ ]:
# Plot feature by importance in this model
plot_df = pd.DataFrame({'feature': X.design_info.column_names, 'importance': clf.feature_importances_})
plt.figure(figsize=(10,10))
sns.barplot(x='importance', y='feature', data=plot_df.sort_values('importance', ascending=False),
color='b')
plt.xticks(rotation=90);